from __future__ import annotations

from typing import Protocol


class IChannel(Protocol):
    name: str

    async def connect(self) -> None: ...
    async def send_message(self, chat_id: str, content: str, msg_type: str = "text") -> None: ...
    async def disconnect(self) -> None: ...
    def is_connected(self) -> bool: ...
